### ISSUE TITLE
Channel returning no results

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Food-Network.bundle#18]
Something has changed with the website resulting in empty results.

**Comment by shopgirl284** [comment]
The website code has changed to become similar to the HGTV channel. So while rewriting the Food Network channel plugin, it is best to take the time to clean up the code for both channels and make them consistent. That way both the Food Network and HGTV channels will be similar and easier to maintain when changes are made to both.

**Comment by shopgirl284** [comment]
This issue is fixed with PR #19 - https://github.com/plexinc-plugins/Food-Network.bundle/pull/19

**Comment by josephrooks** [comment]
@shopgirl284 This issue isn't fixed yet (or has re-broken since) – still returning no results.
